### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by fareshan** [elecfreaks/pxt-cutebotpro#3]
Can you add the French translations ?

**Comment by elecfreaks1** [comment]
Thank you for your suggestion, please contact the following email address, he will handle it

support@elecfreaks.com

**Comment by fareshan** [comment]
Thanks, I just sent the email. You can also notice that I wrote translations in a pull request.
https://github.com/elecfreaks/pxt-Cutebot-Pro/pull/2
