### ISSUE TITLE
Bug: Case 04 in the manual doesn't start cruising again

### ISSUE THREAD

**Issue by dannystaple** [elecfreaks/pxt-cutebotpro#4]
Using the code from Case 4 in the manual, the Automatic Obstacle avoidance, the robot appears to stop and turn at any obstacle (or anything in sensor range), but then does not start cruising again.

<img width="794" alt="Screenshot 2023-12-26 at 14 19 48" src="https://github.com/elecfreaks/pxt-Cutebot-Pro/assets/426859/015fdd10-8efc-4097-97fd-f446932b1a15">

Python code (based on the same makecode blocks as the manual):

```python
basic.show_icon(IconNames.HEART)

def on_forever():
    sonar_reading = CutebotPro.ultrasonic(SonarUnit.CENTIMETERS)
    if sonar_reading > 2 and sonar_reading < 20:
        CutebotPro.trolley_steering(CutebotProTurn.LEFT_IN_PLACE, CutebotProAngle.ANGLE180)
    else:
        CutebotPro.cruise_control(30, 30, CutebotProSpeedUnits.CMS)
basic.forever(on_forever)
```

What I expected:
- After the object is detected, and the "trolley steering" turn is made
- The else will be active and the robot will start "cruising" at pwm 30 with both motors.

What happens:
- After the object is detected, and the "trolley steering" turn is made
- The robot does not start cruising again.
- If I put an object in front of the sensor, it does make the turn again, so the loop is running.

I am happy to work with someone testing code on my CuteBot Pro and Microbit V2 setup to find out why it's doing this.

**Comment by elecfreaks1** [comment]
Thank you for your question. I'll arrange for someone to investigate the cause
